# Docs for Azure Web Apps Deploy Action: https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - EventServiceApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Optional)
        run: |
          echo "Running tests..."
          # Example: pytest tests/

    - name: Zip artifact for deployment
  run: |
    zip -r release.zip . -x "venv/*" "__pycache__/*" ".git/*" "*.md"

- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'userserviceapp'
    slot-name: 'Production'
    package: ./release.zip
    clean: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT-based authentication

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Login to Azure
  uses: azure/login@v2
  with:
    client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
    tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
    subscription-id: a38ee98b-f8ff-483c-a391-7bf174f6b88a


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'EventServiceApp'
          # Remove slot-name unless you explicitly have slots
          package: .

